/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermeniRouteImport } from './routes/termeni'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as ConfidentialitateRouteImport } from './routes/confidentialitate'
import { Route as IndexRouteImport } from './routes/index'

const TermeniRoute = TermeniRouteImport.update({
  id: '/termeni',
  path: '/termeni',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialitateRoute = ConfidentialitateRouteImport.update({
  id: '/confidentialitate',
  path: '/confidentialitate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/gdpr': typeof GdprRoute
  '/termeni': typeof TermeniRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/gdpr': typeof GdprRoute
  '/termeni': typeof TermeniRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/gdpr': typeof GdprRoute
  '/termeni': typeof TermeniRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/confidentialitate' | '/gdpr' | '/termeni'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/confidentialitate' | '/gdpr' | '/termeni'
  id: '__root__' | '/' | '/confidentialitate' | '/gdpr' | '/termeni'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfidentialitateRoute: typeof ConfidentialitateRoute
  GdprRoute: typeof GdprRoute
  TermeniRoute: typeof TermeniRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termeni': {
      id: '/termeni'
      path: '/termeni'
      fullPath: '/termeni'
      preLoaderRoute: typeof TermeniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialitate': {
      id: '/confidentialitate'
      path: '/confidentialitate'
      fullPath: '/confidentialitate'
      preLoaderRoute: typeof ConfidentialitateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfidentialitateRoute: ConfidentialitateRoute,
  GdprRoute: GdprRoute,
  TermeniRoute: TermeniRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
